# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc51b8f9f42abd5fabba80185f34e96662dbb6d5c97496c832fe9af87455726c04ccc55317495b2090b4f241a4d4aded3dfb1665ff1869708d520f02986054ad

test:
  secret_key_base: ea2d95c2129f217cd732e60d4ecfd8dd74c203813cb62e22409996fe4c49a835b5493816c9ef05aeb9eff0b2c0be506bb84dfaa2641387673e0fa09b3e3e8427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
